import csv
import sqlite3

connection = sqlite3.connect("../data.sqlite")
cursor = connection.cursor()
cursor.execute('''CREATE TABLE IF NOT EXISTS data ("Absence End" text,
     "Absence Start" text,
     "Admin/Prog" text,
     "Age" text,
     "Annual salary" text,
     "Appointed (ERP) GOR" text,
     "Appointed (ERP) Office Name" text,
     "Appointed (ERP) Office Postcode" text,
     "Appointed (ERP) Office Town" text,
     "BP Pack Dir" text,
     "BU Breakdown" text,
     "Chief Position" text,
     "Contract Type" text,
     "Cost Centre Name" text,
     "Cost Code" text,
     "Date of Birth" text,
     "Date to CS" text,
     "Directorate" text,
     "Disability Status" text,
     "Disability" text,
     "Disabilty Updated" text,
     "Distribution BU" text,
     "Employee Group" text,
     "Employment Status" text,
     "End of TP" text,
     "Entry Date" text,
     "Ethnic Origin" text,
     "Ethnicity Status" text,
     "Ethnicity Updated" text,
     "FT/PT" text,
     "FTA End Date" text,
     "FTE" text,
     "First Name" text,
     "Full Name" text,
     "GSI Address" text,
     "Gender" text,
     "Grade" text,
     "HMRC Grade" text,
     "Half Pay Start" text,
     "Initial start date" text,
     "Last Name" text,
     "Line Manager GSI Address" text,
     "Line Manager Grade" text,
     "Line Manager Name" text,
     "Line Manager PID" text,
     "Line of Business" text,
     "Marital status" text,
     "NINO" text,
     "Name" text,
     "National Identity" text,
     "Nationality" text,
     "No Pay Date" text,
     "OfficeLat" text,
     "OfficeLong" text,
     "Organizational Unit Text" text,
     "Organizational Unit" text,
     "PIDNo" text,
     "Partial retirement date" text,
     "Pay Scale Area" text,
     "Pay Scale Group" text,
     "Pay Scale Level" text,
     "Pay Scale Type" text,
     "Payroll Area" text,
     "Pension Rate End" text,
     "Pension Rate Start" text,
     "Perm/Temp" text,
     "Personnel Subarea" text,
     "Position Text" text,
     "Position" text,
     "PreSurplus Start Date" text,
     "Profession" text,
     "Redeployment Start Date" text,
     "Redeployment Status" text,
     "Religion Or Belief Category" text,
     "Religion Or Belief Updated" text,
     "Religion Or Belief" text,
     "SIP Grade (FTA)" text,
     "SIP" text,
     "Sexual Orientation Category" text,
     "Sexual Orientation Updated" text,
     "Sexual Orientation" text,
     "SiP Grade" text,
     "Start of TP text",
     "Steps Code" text,
     "Sub-Directorate Group" text,
     "Surplus start Date" text,
     "Temp Promotion Grade" text,
     "Temp Promotion Reason" text,
     "Temp Promotion" text,
     "Type of Pay" text,
     "Weekly Hrs" text,
     "Work schedule rule" text,
     "Work schedule" text,
     "Years in CS" text)''')

data_file = open("data.csv")
rows = csv.reader(data_file)
next(rows)
cursor.executemany(
    "INSERT INTO data VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
    "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
    rows)

connection.commit()
connection.close()
